export const sampleProducts = [
  {
    id: "1",
    name: "Basmati Rice 5kg",
    category: "Grains",
    hsn: "1006",
    purchasePrice: 280,
    sellingPrice: 350,
    mrp: 380,
    gstRate: 5,
    stock: 45,
    unit: "Bag",
  },
  {
    id: "2",
    name: "Sunflower Oil 1L",
    category: "Oils",
    hsn: "1512",
    purchasePrice: 140,
    sellingPrice: 170,
    mrp: 185,
    gstRate: 5,
    stock: 3,
    unit: "Bottle",
  },
  {
    id: "3",
    name: "Toor Dal 1kg",
    category: "Pulses",
    hsn: "0713",
    purchasePrice: 115,
    sellingPrice: 145,
    mrp: 155,
    gstRate: 5,
    stock: 28,
    unit: "Kg",
  },
  {
    id: "4",
    name: "Amul Butter 500g",
    category: "Dairy",
    hsn: "0405",
    purchasePrice: 240,
    sellingPrice: 280,
    mrp: 295,
    gstRate: 12,
    stock: 0,
    unit: "Pack",
  },
  {
    id: "5",
    name: "Surf Excel 1kg",
    category: "Cleaning",
    hsn: "3402",
    purchasePrice: 185,
    sellingPrice: 220,
    mrp: 240,
    gstRate: 18,
    stock: 15,
    unit: "Pack",
  },
  {
    id: "6",
    name: "Colgate 200g",
    category: "Personal Care",
    hsn: "3306",
    purchasePrice: 85,
    sellingPrice: 105,
    mrp: 115,
    gstRate: 18,
    stock: 2,
    unit: "Tube",
  },
  {
    id: "7",
    name: "Parle-G Biscuits",
    category: "Snacks",
    hsn: "1905",
    purchasePrice: 8,
    sellingPrice: 12,
    mrp: 15,
    gstRate: 12,
    stock: 120,
    unit: "Pack",
  },
  {
    id: "8",
    name: "Maggi Noodles 12pk",
    category: "Instant Food",
    hsn: "1902",
    purchasePrice: 120,
    sellingPrice: 155,
    mrp: 168,
    gstRate: 12,
    stock: 8,
    unit: "Box",
  },
];

export const sampleCustomers = [
  {
    id: "c1",
    name: "Rajesh Kumar",
    phone: "9876543210",
    email: "rajesh@email.com",
    address: "MG Road, Bangalore",
    gstin: "",
  },
  {
    id: "c2",
    name: "Priya Sharma",
    phone: "9865432109",
    email: "priya@email.com",
    address: "Anna Nagar, Chennai",
    gstin: "",
  },
  {
    id: "c3",
    name: "Arun Enterprises",
    phone: "9754321098",
    email: "arun@biz.com",
    address: "Linking Road, Mumbai",
    gstin: "27AABCU9603R1ZX",
  },
  {
    id: "c4",
    name: "Meera Textiles",
    phone: "9643210987",
    email: "meera@textiles.com",
    address: "Sadar Bazar, Delhi",
    gstin: "07AAFCM1234B1Z5",
  },
];

export const sampleVendors = [
  {
    id: "v1",
    name: "Delhi Wholesale Traders",
    phone: "9111234567",
    email: "dwt@vendor.com",
    address: "Chandni Chowk, Delhi",
    gstin: "07AABCT1234B1Z5",
    outstanding: 45000,
  },
  {
    id: "v2",
    name: "Mumbai Food Distributors",
    phone: "9222345678",
    email: "mfd@vendor.com",
    address: "Crawford Market, Mumbai",
    gstin: "27AABCM5678C1Z3",
    outstanding: 28500,
  },
  {
    id: "v3",
    name: "Spice Garden Suppliers",
    phone: "9333456789",
    email: "sgs@vendor.com",
    address: "Khari Baoli, Delhi",
    gstin: "07AABCS9012D1Z1",
    outstanding: 12000,
  },
];

export const sampleInvoices = [
  {
    id: "inv1",
    invoiceNo: "INV-2024-001",
    customerId: "c1",
    customerName: "Rajesh Kumar",
    date: "2024-01-15",
    items: [
      {
        name: "Basmati Rice 5kg",
        qty: 2,
        price: 350,
        discount: 0,
        gstRate: 5,
        amount: 700,
      },
      {
        name: "Toor Dal 1kg",
        qty: 3,
        price: 145,
        discount: 0,
        gstRate: 5,
        amount: 435,
      },
    ],
    subtotal: 1135,
    cgst: 28.38,
    sgst: 28.38,
    igst: 0,
    total: 1191.76,
    paymentMode: "Cash",
    status: "Paid",
  },
  {
    id: "inv2",
    invoiceNo: "INV-2024-002",
    customerId: "c2",
    customerName: "Priya Sharma",
    date: "2024-01-16",
    items: [
      {
        name: "Sunflower Oil 1L",
        qty: 3,
        price: 170,
        discount: 0,
        gstRate: 5,
        amount: 510,
      },
      {
        name: "Amul Butter 500g",
        qty: 2,
        price: 280,
        discount: 0,
        gstRate: 12,
        amount: 560,
      },
    ],
    subtotal: 1070,
    cgst: 46.05,
    sgst: 46.05,
    igst: 0,
    total: 1162.1,
    paymentMode: "UPI",
    status: "Paid",
  },
  {
    id: "inv3",
    invoiceNo: "INV-2024-003",
    customerId: "c3",
    customerName: "Arun Enterprises",
    date: "2024-01-17",
    items: [
      {
        name: "Surf Excel 1kg",
        qty: 10,
        price: 220,
        discount: 5,
        gstRate: 18,
        amount: 2090,
      },
      {
        name: "Colgate 200g",
        qty: 20,
        price: 105,
        discount: 0,
        gstRate: 18,
        amount: 2100,
      },
    ],
    subtotal: 4190,
    cgst: 0,
    sgst: 0,
    igst: 754.2,
    total: 4944.2,
    paymentMode: "Credit",
    status: "Pending",
  },
  {
    id: "inv4",
    invoiceNo: "INV-2024-004",
    customerId: "c4",
    customerName: "Meera Textiles",
    date: "2024-01-10",
    items: [
      {
        name: "Parle-G Biscuits",
        qty: 50,
        price: 12,
        discount: 0,
        gstRate: 12,
        amount: 600,
      },
    ],
    subtotal: 600,
    cgst: 0,
    sgst: 0,
    igst: 72,
    total: 672,
    paymentMode: "Credit",
    status: "Overdue",
  },
  {
    id: "inv5",
    invoiceNo: "INV-2024-005",
    customerId: "c1",
    customerName: "Rajesh Kumar",
    date: "2024-01-18",
    items: [
      {
        name: "Maggi Noodles 12pk",
        qty: 5,
        price: 155,
        discount: 0,
        gstRate: 12,
        amount: 775,
      },
    ],
    subtotal: 775,
    cgst: 46.5,
    sgst: 46.5,
    igst: 0,
    total: 868,
    paymentMode: "Cash",
    status: "Paid",
  },
];

export const sampleExpenses = [
  {
    id: "e1",
    category: "Rent",
    description: "Shop rent Jan 2024",
    amount: 15000,
    date: "2024-01-01",
    paymentMode: "Bank Transfer",
  },
  {
    id: "e2",
    category: "Utilities",
    description: "Electricity bill",
    amount: 3200,
    date: "2024-01-05",
    paymentMode: "Online",
  },
  {
    id: "e3",
    category: "Salaries",
    description: "Staff salaries Jan",
    amount: 25000,
    date: "2024-01-31",
    paymentMode: "Bank Transfer",
  },
  {
    id: "e4",
    category: "Marketing",
    description: "Pamphlet printing",
    amount: 1500,
    date: "2024-01-12",
    paymentMode: "Cash",
  },
  {
    id: "e5",
    category: "Misc",
    description: "Stationery and bags",
    amount: 800,
    date: "2024-01-20",
    paymentMode: "Cash",
  },
];

export const samplePurchases = [
  {
    id: "po1",
    poNo: "PO-2024-001",
    vendorId: "v1",
    vendorName: "Delhi Wholesale Traders",
    date: "2024-01-08",
    items: [
      {
        name: "Basmati Rice 5kg",
        qty: 20,
        purchasePrice: 280,
        gstRate: 5,
        amount: 5600,
      },
      {
        name: "Toor Dal 1kg",
        qty: 30,
        purchasePrice: 115,
        gstRate: 5,
        amount: 3450,
      },
    ],
    subtotal: 9050,
    totalGst: 452.5,
    total: 9502.5,
    status: "Received",
  },
  {
    id: "po2",
    poNo: "PO-2024-002",
    vendorId: "v2",
    vendorName: "Mumbai Food Distributors",
    date: "2024-01-12",
    items: [
      {
        name: "Sunflower Oil 1L",
        qty: 24,
        purchasePrice: 140,
        gstRate: 5,
        amount: 3360,
      },
      {
        name: "Amul Butter 500g",
        qty: 12,
        purchasePrice: 240,
        gstRate: 12,
        amount: 2880,
      },
    ],
    subtotal: 6240,
    totalGst: 428.4,
    total: 6668.4,
    status: "Pending",
  },
];

export const sampleVendorPayments = [
  {
    id: "vp1",
    vendorId: "v1",
    vendorName: "Delhi Wholesale Traders",
    amount: 9502.5,
    date: "2024-01-15",
    mode: "NEFT",
    reference: "TXN123456",
    notes: "PO-2024-001 payment",
  },
  {
    id: "vp2",
    vendorId: "v2",
    vendorName: "Mumbai Food Distributors",
    amount: 5000,
    date: "2024-01-18",
    mode: "UPI",
    reference: "UPI789012",
    notes: "Advance for PO-2024-002",
  },
];

export const monthlyData = [
  { month: "Aug", sales: 82000, purchases: 65000 },
  { month: "Sep", sales: 95000, purchases: 72000 },
  { month: "Oct", sales: 88000, purchases: 68000 },
  { month: "Nov", sales: 115000, purchases: 85000 },
  { month: "Dec", sales: 142000, purchases: 95000 },
  { month: "Jan", sales: 98000, purchases: 74000 },
];
